name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Install dependencies
        run: cd app && npm ci
      - name: Run tests
        run: cd app && npm test
      - name: Publish coverage
        uses: coverallsapp/github-action@v2.2.0
